---
- hosts: devstack
  vars:
    password: stack
    local_ssh_pubkey: ~/.ssh/id_rsa.pub
    dest: /opt/stack
    service_token: tokentoken
    swift_hash: 66a3d6b56c1f479c8b4e70ab5c2000f5
    swift_replicas: 1
    branch: stable/icehouse
    reclone: yes
    api_rate_limit: False
    logdays: 2
  remote_user: vagrant
  tasks:

  # - name: update aptitude cache
  #   raw: apt-get update

  - name: install python-apt for ansible
    raw: apt-get install python-apt

  - name: ensure git is at the latest version
    apt: name=git state=latest

  - git: repo=https://github.com/openstack-dev/devstack.git
         dest=/home/vagrant/devstack
         version=stable/icehouse

  - name: patch stack.sh to use correct version of pip
    action: shell awk '/install_pip.sh/ { print; print "sudo pip install --upgrade setuptools"; next }1' stack.sh > patched_stack.sh

  - name: install devstack
    template: src=templates/devstack.j2 dest=/home/vagrant/devstack/local.conf

  # Run the patched stack.sh cmd
  - shell: patch_stack.sh >> patched_stack.sh.log chdir=/home/vagrant/devstack/
